# docker-compose.deploy.yml
version: '3.8'

services:
  app:
    image: lucaferro3101/kiruna-client:latest
    ports:
      - "5173:5173"  # Map host port 5173 to client container port
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    networks:
      - app-network

  server:
    image: lucaferro3101/kiruna-server:latest
    ports:
      - "3001:3001"  # Map host port 3001 to server container port
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql  # Set MySQL hostname to service name
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=kiruna_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kiruna_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local