# my-node-app/docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Map host port 3000 to client container port
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    networks:
      - app-network
    command: ["npm", "run", "dev", "--", "--host"]

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3001:3001"  # Map host port 5000 to server container port
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql  # Set MySQL hostname to service name
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=kiruna_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: ["nodemon", "--watch", ".", "--exec", "node", "./src/index.mjs"]

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kiruna_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
